# Generated by Django 5.2.16 on 2026-08-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("script_consent", "0002_seed_demo_snippets"),
    ]

    operations = [
        migrations.AddField(
            model_name="bannerconfig",
            name="accept_all",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Accept all"
            ),
        ),
        migrations.AddField(
            model_name="bannerconfig",
            name="custom_saves",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Selected saved"
            ),
        ),
        migrations.AddField(
            model_name="bannerconfig",
            name="dismissals",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Explicit closes"
            ),
        ),
        migrations.AddField(
            model_name="bannerconfig",
            name="impressions",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Banner impressions"
            ),
        ),
        migrations.AddField(
            model_name="bannerconfig",
            name="necessary_only",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="Necessary only"
            ),
        ),
        migrations.AddField(
            model_name="bannerconfig",
            name="operator",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Legal operator details shown in the banner footer. Leave empty to omit.",
                verbose_name="Operator",
            ),
        ),
        migrations.AddField(
            model_name="scriptsnippet",
            name="recipient",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Data recipient shown in the banner for this snippet's category. Leave empty to omit.",
                max_length=255,
                verbose_name="Recipient",
            ),
        ),
    ]
