# Generated by Django 5.2.16 on 2026-08-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("script_consent", "0003_banner_operator_recipient_stats"),
    ]

    operations = [
        migrations.AddField(
            model_name="bannerconfig",
            name="privacy_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Link shown in the banner. Changing it increments the banner version and invalidates prior consents. Leave empty to hide the link. Relative paths and http(s) only.",
                max_length=512,
                verbose_name="Privacy policy URL",
            ),
        ),
    ]
